#ifndef JENKINSPLUGIN_GLOBAL_H
#define JENKINSPLUGIN_GLOBAL_H

#include <QtGlobal>

#if defined(JENKINSPLUGIN_LIBRARY)
#  define JENKINSPLUGINSHARED_EXPORT Q_DECL_EXPORT
#else
#  define JENKINSPLUGINSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // JENKINSPLUGIN_GLOBAL_H
